### ISSUE TITLE
Here is non-less file issue

### ISSUE THREAD

**Issue by romanran** [just-boris/less-plugin-glob#12]
Hi,
when I do `@import (less)` to treat css files as less, the plugin halts whole build
I've found this function:
`function isLess(file) {
    return path.extname(file) === '.less';
}`
can you detect the `(less)` flag and add .css to extension the check please?

Edit:
[I've made the change(minus the (less) detection flag) ](https://github.com/romanran/less-plugin-glob/tree/feature/css) you can check it out here

**Comment by just-boris** [comment]
Released as `v2.0.0`, because new behavior is definitely breaking change
