### ISSUE TITLE
Absolute paths are broken.

### ISSUE THREAD

**Issue by carlosl** [just-boris/less-plugin-glob#14]
It does not seem to detect absolute paths correctly and ends up pre-pending the basePath.

**Comment by thorn0** [comment]
I'm probably having the same issue. On Windows, after update to 2.0.0, I'm getting things like: `background:url(../../d:/dev/foo/srcui/images/default/avatar.gif)`
I have `relativeUrls: true` if it matters. Had to switch back to 1.1.1.

**Comment by Remownz** [comment]
same here: 
@import "base/*.less";

generates absolute paths: /Users/[...]/Workspace/[..]/frontend/src/less/base/[...].less

all fine with 1.1.1
