### ISSUE TITLE
make compatible with grunt-contrib-less

### ISSUE THREAD

**Issue by vospascal** [just-boris/less-plugin-glob#3]
just-boris i use grunt-contrib-less  they have a example how to load plugin's like this:

plugins: [
        new (require('less-plugin-autoprefix'))({browsers: ["last 2 versions"]}),
        new (require('less-plugin-clean-css'))(cleanCssOptions)
      ],

How would i load your wonderfull plugin in here so that it works with grunt-contrib-less?

**Comment by just-boris** [comment]
You can use my plugin like so:
```
plugins: [
require('less-plugin-glob')
],
```
That's why it does't have any options. So I looked on [less-plugin-inline-urls](https://github.com/less/less-plugin-inline-urls) when was writing this one.
