### ISSUE TITLE
Globbing Not Functioning

### ISSUE THREAD

**Issue by SpencerCarstens** [just-boris/less-plugin-glob#4]
I can't get your plugin to work... I assume I'm doing something wrong.

Has anyone else gotten it to work?

Not getting any errors... just no output when I try to use globbing.

```
gulp.task( 'styles', () => {
  return gulp.src( [ 'app/styles/main.less' ] )
    .pipe( $.less( {
      plugins: [ require( 'less-plugin-glob' ) ],
    } ) )
    .pipe( gulp.dest( 'dist/styles' ) );
} );
```
```
// main.less
// Each line below is tried on it's own of course.
@import "app/module/waffle.less"; // Works
@import "app/module/**"; // Does not work.
@import "app/module/**/*"; // Does not work.
@import "app/module/**/*.less"; // Does not work.
```

**Comment by iamfrontender** [comment]
I just met exactly the same behaviour. Also noticed that less won't add rules from globbed files if they're empty.

**Comment by sonicparke** [comment]
I'm getting the same here as well.

**Comment by just-boris** [comment]
Well, so many people encountered that issue. But I have the same setup and it is work well

**Comment by just-boris** [comment]
Fine, got it.
Why are you imports declared from the app root?  You should import relatively to this file.

**Comment by andyblount** [comment]
Had the same problem but as Boris says if you import relative to the file it works.

Is is possible to add functionality to make it work from the app root as well?

**Comment by just-boris** [comment]
Found that less implicitly adds extra path to search files [here](https://github.com/less/less.js/blob/master/lib%2Fless-node%2Ffile-manager.js#L39)
```
if (!isAbsoluteFilename && paths.indexOf('.') === -1) { 
  paths.push('.'); 
}
```

I can't reuse this piece of code, only copy that to my plugin. I'll try to do it

**Comment by just-boris** [comment]
Seems to be fixed in my little example.
Please try to test current master in your projects, and if it is fine, I will make a release
